"""add board persona

Revision ID: 25f7e69101ae
Revises: c8d1d036b9d3
Create Date: 2026-10-07 16:36:50.036326

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25f7e69101ae"
down_revision: str | Sequence[str] | None = "c8d1d036b9d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("boards", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("persona_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("boards", schema=None) as batch_op:
        batch_op.drop_column("persona_id")

    # ### end Alembic commands ###
